name: Continuous Integration Pipeline
on: 
  pull_request:
    paths:
    - '**.py'
jobs:
  formatting:
    name: Autoyapf PEP-8 Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.head_ref }}'
      - name: Importing formatting
        uses: mritunjaysharma394/autoyapf@v2
        with:
          args: '--style pep8 --recursive --in-place .'
      - name: Checking for modified files
        run: >-
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --;
          then echo "false"; else echo "true"; fi)
      - name: Pushing changes
        if: steps.git-check.outputs.modified == 'true'
        run: >
          git config --global user.name github-actions

          git config --global user.email
          '${GITHUB_ACTOR}@users.noreply.github.com'  

          git remote set-url origin https://x-access-token:${{
          secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git commit -am "Automated autoyapf fixes"

          git push
